from .auth import auth_bp
from .subject import subject_bp
from .user import user_bp
from .admin import admin_bp
from .teacher import teacher_bp
from .student import student_bp
from .debug import debug_bp
from .classes import class_bp
from .recognition import recognition_bp